"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, CarFront, Coffee, ShoppingBasket, Music2, Plane, Scissors, House, Phone, Utensils, Bike, Stethoscope, Pill, UsersRound, Mic, MessageCircle, MapPin } from "lucide-react";
import { LANGUAGES } from "@/lib/languages";
import { PERSONAS, personaId, type PersonaMeta } from "@/lib/personas.generated";
import { SCENARIO_ORDER, type Lang, type ShopId } from "@/lib/maatu-design";

export const SCENE_ICONS: Record<string, typeof Coffee> = { auto: CarFront, chai: Coffee, market: ShoppingBasket, gate: Bike, phone: Phone, music: Music2, airport: Plane, salon: Scissors, kirana: ShoppingBasket, clinic: Stethoscope, restaurant: Utensils, neighbour: UsersRound, landlord: House, pharmacy: Pill };
const NAME: Record<ShopId, string> = { auto: "A ride across town", chai: "A little café conversation", market: "At the local market", gate: "Your delivery is here", phone: "Sort out your connection", music: "Teach what you love", airport: "Ready for takeoff", salon: "A haircut & a chat", kirana: "The neighborhood shop", clinic: "At the clinic", restaurant: "Order something delicious", neighbour: "Meet the neighbors", landlord: "A little repair at home", pharmacy: "At the pharmacy" };
const TASKS: Record<string, string[]> = { auto: ["Say where you want to go", "Ask about the fare", "Keep the small talk going"], chai: ["Say hello", "Talk about your day", "Ask a question back"], market: ["Ask what is fresh", "Find out the price", "Choose what to buy"], music: ["Explain a simple idea", "Answer a curious question", "Help your student try it"] };
const GROUPS = ["All scenes", "Everyday", "Out & about", "Music"];
const SCENE_PHOTOS: Record<string, string> = { "ta-chai": "ta-chai", "ta-market": "ta", "kn-market": "kn", "kn-auto": "kn-auto", "hi-market": "hi", "fr-chai": "fr", "fr-market": "fr-market" };
export default function ScenarioStudio({ lang, onStart, onText, onCustom }: { lang: Lang; onStart: (persona: PersonaMeta) => void; onText: (persona: PersonaMeta) => void; onCustom: (context: string) => void }) {
  const l = LANGUAGES[lang];
  const [selected, setSelected] = useState<ShopId | null>(null);
  const [group, setGroup] = useState("All scenes");
  const [custom, setCustom] = useState("");
  const meta = selected ? PERSONAS[personaId(selected, lang) ?? ""] : null;
  const filter = (id: ShopId) => group === "All scenes" || (group === "Music" ? id === "music" : group === "Out & about" ? ["auto", "airport", "market", "salon", "restaurant"].includes(id) : !["auto", "airport", "music"].includes(id));
  const featured: ShopId[] = ["chai", "market", "auto"];
  if (meta && selected) {
    const Icon = SCENE_ICONS[selected];
    const photograph = SCENE_PHOTOS[`${lang}-${selected}`];
    return <div className="scene-preview"><button type="button" className="text-button" onClick={() => setSelected(null)}><ArrowLeft size={17}/> All scenes</button><div className={`scene-cover scene-${selected} ${photograph ? "has-photo" : ""}`} style={photograph ? { backgroundImage: `url(/scenes/${photograph}.webp)` } : undefined}><Icon size={74} strokeWidth={1.2}/><span><MapPin size={16}/>{meta.sceneLabel}</span></div><header className="page-heading"><h1>{NAME[selected]}</h1><p>Practise with {meta.name}, your AI scene partner. Take your words out into the world.</p></header><p className="scene-description">{lang === "fr" ? `An everyday ${meta.sceneLabel.toLowerCase()} conversation. Use vous with someone you’ve just met, listen for the next question, and ask for help whenever you need it.` : `An everyday encounter in ${l.city}, with the words people actually use. ${meta.teachMode ? "You are the teacher, and your curious student asks the questions." : "Keep it natural. Your character stays in the scene and helps you find a way forward."}`}</p><div className="scene-goals"><h3>Give these a try</h3>{(TASKS[selected] ?? meta.rubric.slice(0, 3).map((x) => x.charAt(0).toUpperCase() + x.slice(1))).map((goal, i) => <p key={goal}><span>{i + 1}</span>{goal}</p>)}</div><div className="preview-actions"><button type="button" className="button button-primary" onClick={() => onStart(meta)}><Mic size={18}/> Step into the scene<ArrowRight size={17}/></button><button type="button" className="button button-outline" onClick={() => onText(meta)}><MessageCircle size={18}/> Try it by text</button></div><p className="composer-hint">Need a hand? “What does that mean?” and “say it again” always work.</p></div>;
  }
  return <>
    <header className="page-heading"><h1>Real places.<br/><em>Real things to say.</em></h1><p>A small adventure in {l.city}. You bring the words, we’ll bring the conversation.</p></header>
    <div className="scene-filters" role="group" aria-label="Filter scenarios">{GROUPS.map((g) => <button type="button" aria-pressed={group === g} key={g} className={group === g ? "active" : ""} onClick={() => setGroup(g)}>{g}</button>)}</div>
    <div className="featured-scenes">{featured.filter(filter).map((id) => { const p = PERSONAS[personaId(id, lang)!]; const Icon = SCENE_ICONS[id]; const photograph = SCENE_PHOTOS[`${lang}-${id}`]; return <button type="button" className={`featured-scene scene-${id}`} key={id} onClick={() => setSelected(id)}><div className={`scene-picture ${photograph ? "has-photo" : ""}`} style={photograph ? { backgroundImage: `url(/scenes/${photograph}.webp)` } : undefined}><Icon size={38} strokeWidth={1.5}/><span><MapPin size={13}/>{l.city}</span></div><div className="scene-card-copy"><h3>{NAME[id]}</h3><span className="scene-category">{id === "auto" ? lang === "fr" ? "Taxi" : "Auto rickshaw" : id === "chai" ? lang === "fr" ? "Café" : "Tea & filter coffee" : "Neighborhood market"}</span><p>Practise with {p.name}, your AI partner.</p><span className="scene-open">Try this scene<ArrowRight size={17}/></span></div></button>; })}</div>
    <div className="scene-list">{SCENARIO_ORDER.filter((id) => !featured.includes(id) && filter(id)).map((id) => { const p = PERSONAS[personaId(id, lang)!]; const Icon = SCENE_ICONS[id]; return <button type="button" key={id} onClick={() => setSelected(id)}><span className="round-icon"><Icon size={24}/></span><span><strong>{NAME[id]}</strong><small>{p.sceneLabel} · AI partner {p.name}</small></span><ArrowRight size={18}/></button>; })}</div>
    <section className="custom-scene"><div><h3>Your imagination is a good place, too.</h3><p>Describe any situation and your teacher will play the other part.</p></div><form onSubmit={(e) => { e.preventDefault(); if (custom.trim()) onCustom(`Let's role-play this scene: ${custom.trim()}. Take the other role and help me learn naturally as we go.`); }}><label className="sr-only" htmlFor="custom-scene">Invent a scenario</label><input id="custom-scene" value={custom} maxLength={500} onChange={(e) => setCustom(e.target.value)} placeholder="I’m ordering a birthday cake…"/><button type="submit" className="icon-button" aria-label="Start custom scenario" disabled={!custom.trim()}><ArrowRight size={19}/></button></form></section>
  </>;
}
