// AUTO-GENERATED by agent/build_personas.py. Do not edit by hand.
// The frontend uses this to route shopfronts and label the Call and Debrief screens.

export type PersonaMeta = {
  id: string;
  language: "kn" | "hi" | "ta";
  languageCode: string;
  languageName: string;
  scenario: string;
  shop: string;
  name: string;
  level: number;
  sceneLabel: string;
  teachMode: boolean;
  rubric: string[];
};

export const PERSONAS: Record<string, PersonaMeta> = {
  "kn-auto": {
    "id": "kn-auto",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "auto",
    "shop": "auto",
    "name": "Manjunath",
    "level": 3,
    "sceneLabel": "Auto rickshaw, Bengaluru",
    "teachMode": false,
    "rubric": [
      "fare negotiation",
      "number fluency",
      "politeness register",
      "response latency"
    ]
  },
  "hi-auto": {
    "id": "hi-auto",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "auto",
    "shop": "auto",
    "name": "Ramesh",
    "level": 3,
    "sceneLabel": "Auto rickshaw, Dilli",
    "teachMode": false,
    "rubric": [
      "fare negotiation",
      "number fluency",
      "politeness register",
      "response latency"
    ]
  },
  "ta-auto": {
    "id": "ta-auto",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "auto",
    "shop": "auto",
    "name": "Murugan",
    "level": 3,
    "sceneLabel": "Auto rickshaw, Chennai",
    "teachMode": false,
    "rubric": [
      "fare negotiation",
      "number fluency",
      "politeness register",
      "response latency"
    ]
  },
  "kn-delivery": {
    "id": "kn-delivery",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "delivery",
    "shop": "gate",
    "name": "Kiran",
    "level": 2,
    "sceneLabel": "Delivery gate, Bengaluru",
    "teachMode": false,
    "rubric": [
      "giving directions",
      "number and address fluency",
      "politeness",
      "clarity"
    ]
  },
  "hi-delivery": {
    "id": "hi-delivery",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "delivery",
    "shop": "gate",
    "name": "Sonu",
    "level": 2,
    "sceneLabel": "Delivery gate, Dilli",
    "teachMode": false,
    "rubric": [
      "giving directions",
      "number and address fluency",
      "politeness",
      "clarity"
    ]
  },
  "ta-delivery": {
    "id": "ta-delivery",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "delivery",
    "shop": "gate",
    "name": "Vignesh",
    "level": 2,
    "sceneLabel": "Delivery gate, Chennai",
    "teachMode": false,
    "rubric": [
      "giving directions",
      "number and address fluency",
      "politeness",
      "clarity"
    ]
  },
  "kn-care": {
    "id": "kn-care",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "care",
    "shop": "phone",
    "name": "Divya",
    "level": 2,
    "sceneLabel": "Customer care, Bengaluru",
    "teachMode": false,
    "rubric": [
      "formal register",
      "number and date fluency",
      "address dictation",
      "comprehension under hold"
    ]
  },
  "hi-care": {
    "id": "hi-care",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "care",
    "shop": "phone",
    "name": "Priya",
    "level": 2,
    "sceneLabel": "Customer care, Dilli",
    "teachMode": false,
    "rubric": [
      "formal register",
      "number and date fluency",
      "address dictation",
      "comprehension under hold"
    ]
  },
  "ta-care": {
    "id": "ta-care",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "care",
    "shop": "phone",
    "name": "Lakshmi",
    "level": 2,
    "sceneLabel": "Customer care, Chennai",
    "teachMode": false,
    "rubric": [
      "formal register",
      "number and date fluency",
      "address dictation",
      "comprehension under hold"
    ]
  },
  "kn-airport": {
    "id": "kn-airport",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "airport",
    "shop": "airport",
    "name": "Anitha",
    "level": 3,
    "sceneLabel": "Airport counter, BLR",
    "teachMode": false,
    "rubric": [
      "request forms",
      "number comprehension",
      "following instructions",
      "courtesy"
    ]
  },
  "hi-airport": {
    "id": "hi-airport",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "airport",
    "shop": "airport",
    "name": "Meena",
    "level": 3,
    "sceneLabel": "Airport counter, Dilli",
    "teachMode": false,
    "rubric": [
      "request forms",
      "number comprehension",
      "following instructions",
      "courtesy"
    ]
  },
  "ta-airport": {
    "id": "ta-airport",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "airport",
    "shop": "airport",
    "name": "Deepa",
    "level": 3,
    "sceneLabel": "Airport counter, MAA",
    "teachMode": false,
    "rubric": [
      "request forms",
      "number comprehension",
      "following instructions",
      "courtesy"
    ]
  },
  "kn-chai": {
    "id": "kn-chai",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "chai",
    "shop": "chai",
    "name": "Shivu",
    "level": 2,
    "sceneLabel": "Chai stall, Bengaluru",
    "teachMode": false,
    "rubric": [
      "conversational flow",
      "asking questions back",
      "everyday vocabulary",
      "confidence"
    ]
  },
  "hi-chai": {
    "id": "hi-chai",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "chai",
    "shop": "chai",
    "name": "Chotu",
    "level": 2,
    "sceneLabel": "Chai stall, Dilli",
    "teachMode": false,
    "rubric": [
      "conversational flow",
      "asking questions back",
      "everyday vocabulary",
      "confidence"
    ]
  },
  "ta-chai": {
    "id": "ta-chai",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "chai",
    "shop": "chai",
    "name": "Selvam",
    "level": 2,
    "sceneLabel": "Tea stall, Chennai",
    "teachMode": false,
    "rubric": [
      "conversational flow",
      "asking questions back",
      "everyday vocabulary",
      "confidence"
    ]
  },
  "kn-teach": {
    "id": "kn-teach",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "teach",
    "shop": "music",
    "name": "Arjun",
    "level": 3,
    "sceneLabel": "Music school, Bengaluru",
    "teachMode": true,
    "rubric": [
      "concept clarity",
      "target-language music vocabulary (flag every English fallback)",
      "pacing",
      "whether questions were truly answered"
    ]
  },
  "hi-teach": {
    "id": "hi-teach",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "teach",
    "shop": "music",
    "name": "Aarav",
    "level": 3,
    "sceneLabel": "Music school, Dilli",
    "teachMode": true,
    "rubric": [
      "concept clarity",
      "target-language music vocabulary (flag every English fallback)",
      "pacing",
      "whether questions were truly answered"
    ]
  },
  "ta-teach": {
    "id": "ta-teach",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "teach",
    "shop": "music",
    "name": "Arun",
    "level": 3,
    "sceneLabel": "Music school, Chennai",
    "teachMode": true,
    "rubric": [
      "concept clarity",
      "target-language music vocabulary (flag every English fallback)",
      "pacing",
      "whether questions were truly answered"
    ]
  }
};

// Which scenario each lit shopfront opens.
export const SHOP_SCENARIO: Record<string, string> = {
  "auto": "auto",
  "gate": "delivery",
  "phone": "care",
  "airport": "airport",
  "chai": "chai",
  "music": "teach"
};

export function personaId(shop: string, lang: string): string | null {
  const scenario = SHOP_SCENARIO[shop];
  if (!scenario) return null;
  const id = `${lang}-${scenario}`;
  return PERSONAS[id] ? id : null;
}
