// AUTO-GENERATED by agent/build_personas.py. Do not edit by hand.
// The frontend uses this to route shopfronts and label the Call and Debrief screens.

export type PersonaMeta = {
  id: string;
  language: "kn" | "hi" | "ta" | "fr";
  languageCode: string;
  languageName: string;
  scenario: string;
  shop: string;
  name: string;
  level: number;
  sceneLabel: string;
  teachMode: boolean;
  rubric: string[];
  defaultSecretAgenda?: string[];
};

export const PERSONAS: Record<string, PersonaMeta> = {
  "kn-auto": {
    "id": "kn-auto",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "auto",
    "shop": "auto",
    "name": "Manjunath",
    "level": 3,
    "sceneLabel": "Auto rickshaw, Bengaluru",
    "teachMode": false,
    "rubric": [
      "fare negotiation",
      "number fluency",
      "politeness register",
      "response latency"
    ],
    "defaultSecretAgenda": [
      "numbers 40 to 90",
      "polite imperative forms",
      "past continuous tense"
    ]
  },
  "hi-auto": {
    "id": "hi-auto",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "auto",
    "shop": "auto",
    "name": "Ramesh",
    "level": 3,
    "sceneLabel": "Auto rickshaw, Dilli",
    "teachMode": false,
    "rubric": [
      "fare negotiation",
      "number fluency",
      "politeness register",
      "response latency"
    ],
    "defaultSecretAgenda": [
      "numbers 40 to 90",
      "polite imperative forms",
      "past continuous tense"
    ]
  },
  "ta-auto": {
    "id": "ta-auto",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "auto",
    "shop": "auto",
    "name": "Murugan",
    "level": 3,
    "sceneLabel": "Auto rickshaw, Chennai",
    "teachMode": false,
    "rubric": [
      "fare negotiation",
      "number fluency",
      "politeness register",
      "response latency"
    ],
    "defaultSecretAgenda": [
      "numbers 40 to 90",
      "polite imperative forms",
      "past continuous tense"
    ]
  },
  "fr-auto": {
    "id": "fr-auto",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "auto",
    "shop": "auto",
    "name": "Luc",
    "level": 3,
    "sceneLabel": "Taxi, Paris",
    "teachMode": false,
    "rubric": [
      "fare negotiation",
      "number fluency",
      "politeness register",
      "response latency"
    ],
    "defaultSecretAgenda": [
      "numbers 40 to 90",
      "polite imperative forms",
      "past continuous tense"
    ]
  },
  "kn-delivery": {
    "id": "kn-delivery",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "delivery",
    "shop": "gate",
    "name": "Kiran",
    "level": 2,
    "sceneLabel": "Delivery gate, Bengaluru",
    "teachMode": false,
    "rubric": [
      "giving directions",
      "number and address fluency",
      "politeness",
      "clarity"
    ],
    "defaultSecretAgenda": [
      "directions and locations",
      "flat and floor numbers",
      "polite requests"
    ]
  },
  "hi-delivery": {
    "id": "hi-delivery",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "delivery",
    "shop": "gate",
    "name": "Sonu",
    "level": 2,
    "sceneLabel": "Delivery gate, Dilli",
    "teachMode": false,
    "rubric": [
      "giving directions",
      "number and address fluency",
      "politeness",
      "clarity"
    ],
    "defaultSecretAgenda": [
      "directions and locations",
      "flat and floor numbers",
      "polite requests"
    ]
  },
  "ta-delivery": {
    "id": "ta-delivery",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "delivery",
    "shop": "gate",
    "name": "Vignesh",
    "level": 2,
    "sceneLabel": "Delivery gate, Chennai",
    "teachMode": false,
    "rubric": [
      "giving directions",
      "number and address fluency",
      "politeness",
      "clarity"
    ],
    "defaultSecretAgenda": [
      "directions and locations",
      "flat and floor numbers",
      "polite requests"
    ]
  },
  "fr-delivery": {
    "id": "fr-delivery",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "delivery",
    "shop": "gate",
    "name": "Yanis",
    "level": 2,
    "sceneLabel": "At the intercom, Paris",
    "teachMode": false,
    "rubric": [
      "giving directions",
      "number and address fluency",
      "politeness",
      "clarity"
    ],
    "defaultSecretAgenda": [
      "directions and locations",
      "flat and floor numbers",
      "polite requests"
    ]
  },
  "kn-care": {
    "id": "kn-care",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "care",
    "shop": "phone",
    "name": "Divya",
    "level": 2,
    "sceneLabel": "Customer care, Bengaluru",
    "teachMode": false,
    "rubric": [
      "formal register",
      "number and date fluency",
      "address dictation",
      "comprehension under hold"
    ],
    "defaultSecretAgenda": [
      "numbers and dates",
      "formal address forms",
      "spelling out an address"
    ]
  },
  "hi-care": {
    "id": "hi-care",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "care",
    "shop": "phone",
    "name": "Priya",
    "level": 2,
    "sceneLabel": "Customer care, Dilli",
    "teachMode": false,
    "rubric": [
      "formal register",
      "number and date fluency",
      "address dictation",
      "comprehension under hold"
    ],
    "defaultSecretAgenda": [
      "numbers and dates",
      "formal address forms",
      "spelling out an address"
    ]
  },
  "ta-care": {
    "id": "ta-care",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "care",
    "shop": "phone",
    "name": "Lakshmi",
    "level": 2,
    "sceneLabel": "Customer care, Chennai",
    "teachMode": false,
    "rubric": [
      "formal register",
      "number and date fluency",
      "address dictation",
      "comprehension under hold"
    ],
    "defaultSecretAgenda": [
      "numbers and dates",
      "formal address forms",
      "spelling out an address"
    ]
  },
  "fr-care": {
    "id": "fr-care",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "care",
    "shop": "phone",
    "name": "Julie",
    "level": 2,
    "sceneLabel": "Customer service, Paris",
    "teachMode": false,
    "rubric": [
      "formal register",
      "number and date fluency",
      "address dictation",
      "comprehension under hold"
    ],
    "defaultSecretAgenda": [
      "numbers and dates",
      "formal address forms",
      "spelling out an address"
    ]
  },
  "kn-airport": {
    "id": "kn-airport",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "airport",
    "shop": "airport",
    "name": "Anitha",
    "level": 3,
    "sceneLabel": "Airport counter, BLR",
    "teachMode": false,
    "rubric": [
      "request forms",
      "number comprehension",
      "following instructions",
      "courtesy"
    ],
    "defaultSecretAgenda": [
      "numbers (seat, gate, weight, kilos)",
      "polite requests",
      "understanding instructions"
    ]
  },
  "hi-airport": {
    "id": "hi-airport",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "airport",
    "shop": "airport",
    "name": "Meena",
    "level": 3,
    "sceneLabel": "Airport counter, Dilli",
    "teachMode": false,
    "rubric": [
      "request forms",
      "number comprehension",
      "following instructions",
      "courtesy"
    ],
    "defaultSecretAgenda": [
      "numbers (seat, gate, weight, kilos)",
      "polite requests",
      "understanding instructions"
    ]
  },
  "ta-airport": {
    "id": "ta-airport",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "airport",
    "shop": "airport",
    "name": "Deepa",
    "level": 3,
    "sceneLabel": "Airport counter, MAA",
    "teachMode": false,
    "rubric": [
      "request forms",
      "number comprehension",
      "following instructions",
      "courtesy"
    ],
    "defaultSecretAgenda": [
      "numbers (seat, gate, weight, kilos)",
      "polite requests",
      "understanding instructions"
    ]
  },
  "fr-airport": {
    "id": "fr-airport",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "airport",
    "shop": "airport",
    "name": "Nora",
    "level": 3,
    "sceneLabel": "Airport check-in, Paris",
    "teachMode": false,
    "rubric": [
      "request forms",
      "number comprehension",
      "following instructions",
      "courtesy"
    ],
    "defaultSecretAgenda": [
      "numbers (seat, gate, weight, kilos)",
      "polite requests",
      "understanding instructions"
    ]
  },
  "kn-chai": {
    "id": "kn-chai",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "chai",
    "shop": "chai",
    "name": "Shivu",
    "level": 2,
    "sceneLabel": "Chai stall, Bengaluru",
    "teachMode": false,
    "rubric": [
      "conversational flow",
      "asking questions back",
      "everyday vocabulary",
      "confidence"
    ],
    "defaultSecretAgenda": [
      "everyday small talk",
      "opinions and preferences",
      "present and past tense mix"
    ]
  },
  "hi-chai": {
    "id": "hi-chai",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "chai",
    "shop": "chai",
    "name": "Chotu",
    "level": 2,
    "sceneLabel": "Chai stall, Dilli",
    "teachMode": false,
    "rubric": [
      "conversational flow",
      "asking questions back",
      "everyday vocabulary",
      "confidence"
    ],
    "defaultSecretAgenda": [
      "everyday small talk",
      "opinions and preferences",
      "present and past tense mix"
    ]
  },
  "ta-chai": {
    "id": "ta-chai",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "chai",
    "shop": "chai",
    "name": "Selvam",
    "level": 2,
    "sceneLabel": "Tea stall, Chennai",
    "teachMode": false,
    "rubric": [
      "conversational flow",
      "asking questions back",
      "everyday vocabulary",
      "confidence"
    ],
    "defaultSecretAgenda": [
      "everyday small talk",
      "opinions and preferences",
      "present and past tense mix"
    ]
  },
  "fr-chai": {
    "id": "fr-chai",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "chai",
    "shop": "chai",
    "name": "Camille",
    "level": 2,
    "sceneLabel": "Café, Paris",
    "teachMode": false,
    "rubric": [
      "conversational flow",
      "asking questions back",
      "everyday vocabulary",
      "confidence"
    ],
    "defaultSecretAgenda": [
      "everyday small talk",
      "opinions and preferences",
      "present and past tense mix"
    ]
  },
  "kn-teach": {
    "id": "kn-teach",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "teach",
    "shop": "music",
    "name": "Arjun",
    "level": 3,
    "sceneLabel": "Music school, Bengaluru",
    "teachMode": true,
    "rubric": [
      "concept clarity",
      "target-language music vocabulary (flag every English fallback)",
      "pacing",
      "whether questions were truly answered"
    ],
    "defaultSecretAgenda": [
      "music vocabulary in the target language",
      "explaining and simplifying",
      "answering why questions"
    ]
  },
  "hi-teach": {
    "id": "hi-teach",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "teach",
    "shop": "music",
    "name": "Aarav",
    "level": 3,
    "sceneLabel": "Music school, Dilli",
    "teachMode": true,
    "rubric": [
      "concept clarity",
      "target-language music vocabulary (flag every English fallback)",
      "pacing",
      "whether questions were truly answered"
    ],
    "defaultSecretAgenda": [
      "music vocabulary in the target language",
      "explaining and simplifying",
      "answering why questions"
    ]
  },
  "ta-teach": {
    "id": "ta-teach",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "teach",
    "shop": "music",
    "name": "Arun",
    "level": 3,
    "sceneLabel": "Music school, Chennai",
    "teachMode": true,
    "rubric": [
      "concept clarity",
      "target-language music vocabulary (flag every English fallback)",
      "pacing",
      "whether questions were truly answered"
    ],
    "defaultSecretAgenda": [
      "music vocabulary in the target language",
      "explaining and simplifying",
      "answering why questions"
    ]
  },
  "fr-teach": {
    "id": "fr-teach",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "teach",
    "shop": "music",
    "name": "Léo",
    "level": 3,
    "sceneLabel": "Music studio, Paris",
    "teachMode": true,
    "rubric": [
      "concept clarity",
      "target-language music vocabulary (flag every English fallback)",
      "pacing",
      "whether questions were truly answered"
    ],
    "defaultSecretAgenda": [
      "music vocabulary in the target language",
      "explaining and simplifying",
      "answering why questions"
    ]
  },
  "kn-market": {
    "id": "kn-market",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "market",
    "shop": "market",
    "name": "Lakshmamma",
    "level": 2,
    "sceneLabel": "Vegetable market, Bengaluru",
    "teachMode": false,
    "rubric": [
      "vegetable vocabulary",
      "numbers and quantities",
      "bargaining confidence",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "vegetable names",
      "numbers, weights and prices",
      "bargaining phrases"
    ]
  },
  "hi-market": {
    "id": "hi-market",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "market",
    "shop": "market",
    "name": "Sunita",
    "level": 2,
    "sceneLabel": "Sabzi mandi, Dilli",
    "teachMode": false,
    "rubric": [
      "vegetable vocabulary",
      "numbers and quantities",
      "bargaining confidence",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "vegetable names",
      "numbers, weights and prices",
      "bargaining phrases"
    ]
  },
  "ta-market": {
    "id": "ta-market",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "market",
    "shop": "market",
    "name": "Meena",
    "level": 2,
    "sceneLabel": "Vegetable market, Chennai",
    "teachMode": false,
    "rubric": [
      "vegetable vocabulary",
      "numbers and quantities",
      "bargaining confidence",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "vegetable names",
      "numbers, weights and prices",
      "bargaining phrases"
    ]
  },
  "fr-market": {
    "id": "fr-market",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "market",
    "shop": "market",
    "name": "Sophie",
    "level": 2,
    "sceneLabel": "Street market, Paris",
    "teachMode": false,
    "rubric": [
      "vegetable vocabulary",
      "numbers and quantities",
      "bargaining confidence",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "vegetable names",
      "numbers, weights and prices",
      "bargaining phrases"
    ]
  },
  "kn-kirana": {
    "id": "kn-kirana",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "kirana",
    "shop": "kirana",
    "name": "Shankar",
    "level": 2,
    "sceneLabel": "Provision store, Bengaluru",
    "teachMode": false,
    "rubric": [
      "grocery vocabulary",
      "numbers and totals",
      "asking for alternatives",
      "everyday politeness"
    ],
    "defaultSecretAgenda": [
      "grocery staples",
      "quantities and packet sizes",
      "asking for and refusing things politely"
    ]
  },
  "hi-kirana": {
    "id": "hi-kirana",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "kirana",
    "shop": "kirana",
    "name": "Gupta ji",
    "level": 2,
    "sceneLabel": "Kirana store, Dilli",
    "teachMode": false,
    "rubric": [
      "grocery vocabulary",
      "numbers and totals",
      "asking for alternatives",
      "everyday politeness"
    ],
    "defaultSecretAgenda": [
      "grocery staples",
      "quantities and packet sizes",
      "asking for and refusing things politely"
    ]
  },
  "ta-kirana": {
    "id": "ta-kirana",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "kirana",
    "shop": "kirana",
    "name": "Raja",
    "level": 2,
    "sceneLabel": "Provision store, Chennai",
    "teachMode": false,
    "rubric": [
      "grocery vocabulary",
      "numbers and totals",
      "asking for alternatives",
      "everyday politeness"
    ],
    "defaultSecretAgenda": [
      "grocery staples",
      "quantities and packet sizes",
      "asking for and refusing things politely"
    ]
  },
  "fr-kirana": {
    "id": "fr-kirana",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "kirana",
    "shop": "kirana",
    "name": "Malik",
    "level": 2,
    "sceneLabel": "Épicerie, Paris",
    "teachMode": false,
    "rubric": [
      "grocery vocabulary",
      "numbers and totals",
      "asking for alternatives",
      "everyday politeness"
    ],
    "defaultSecretAgenda": [
      "grocery staples",
      "quantities and packet sizes",
      "asking for and refusing things politely"
    ]
  },
  "kn-doctor": {
    "id": "kn-doctor",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "doctor",
    "shop": "clinic",
    "name": "Dr Geetha",
    "level": 3,
    "sceneLabel": "Clinic, Bengaluru",
    "teachMode": false,
    "rubric": [
      "describing symptoms",
      "time and frequency words",
      "understanding instructions",
      "asking the doctor to repeat"
    ],
    "defaultSecretAgenda": [
      "body parts and symptoms",
      "duration and frequency of time",
      "understanding instructions"
    ]
  },
  "hi-doctor": {
    "id": "hi-doctor",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "doctor",
    "shop": "clinic",
    "name": "Dr Sharma",
    "level": 3,
    "sceneLabel": "Clinic, Dilli",
    "teachMode": false,
    "rubric": [
      "describing symptoms",
      "time and frequency words",
      "understanding instructions",
      "asking the doctor to repeat"
    ],
    "defaultSecretAgenda": [
      "body parts and symptoms",
      "duration and frequency of time",
      "understanding instructions"
    ]
  },
  "ta-doctor": {
    "id": "ta-doctor",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "doctor",
    "shop": "clinic",
    "name": "Dr Rekha",
    "level": 3,
    "sceneLabel": "Clinic, Chennai",
    "teachMode": false,
    "rubric": [
      "describing symptoms",
      "time and frequency words",
      "understanding instructions",
      "asking the doctor to repeat"
    ],
    "defaultSecretAgenda": [
      "body parts and symptoms",
      "duration and frequency of time",
      "understanding instructions"
    ]
  },
  "fr-doctor": {
    "id": "fr-doctor",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "doctor",
    "shop": "clinic",
    "name": "Élodie",
    "level": 3,
    "sceneLabel": "Clinic reception, Paris",
    "teachMode": false,
    "rubric": [
      "describing symptoms",
      "time and frequency words",
      "understanding instructions",
      "asking the doctor to repeat"
    ],
    "defaultSecretAgenda": [
      "body parts and symptoms",
      "duration and frequency of time",
      "understanding instructions"
    ]
  },
  "kn-restaurant": {
    "id": "kn-restaurant",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "restaurant",
    "shop": "restaurant",
    "name": "Ganesh",
    "level": 2,
    "sceneLabel": "Darshini, Bengaluru",
    "teachMode": false,
    "rubric": [
      "food vocabulary",
      "ordering and requesting",
      "handling a change of plan",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "food and drink names",
      "likes, dislikes and quantities",
      "polite requests"
    ]
  },
  "hi-restaurant": {
    "id": "hi-restaurant",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "restaurant",
    "shop": "restaurant",
    "name": "Vikas",
    "level": 2,
    "sceneLabel": "Dhaba, Dilli",
    "teachMode": false,
    "rubric": [
      "food vocabulary",
      "ordering and requesting",
      "handling a change of plan",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "food and drink names",
      "likes, dislikes and quantities",
      "polite requests"
    ]
  },
  "ta-restaurant": {
    "id": "ta-restaurant",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "restaurant",
    "shop": "restaurant",
    "name": "Saravanan",
    "level": 2,
    "sceneLabel": "Mess, Chennai",
    "teachMode": false,
    "rubric": [
      "food vocabulary",
      "ordering and requesting",
      "handling a change of plan",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "food and drink names",
      "likes, dislikes and quantities",
      "polite requests"
    ]
  },
  "fr-restaurant": {
    "id": "fr-restaurant",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "restaurant",
    "shop": "restaurant",
    "name": "Hugo",
    "level": 2,
    "sceneLabel": "Bistro, Paris",
    "teachMode": false,
    "rubric": [
      "food vocabulary",
      "ordering and requesting",
      "handling a change of plan",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "food and drink names",
      "likes, dislikes and quantities",
      "polite requests"
    ]
  },
  "kn-neighbour": {
    "id": "kn-neighbour",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "neighbour",
    "shop": "neighbour",
    "name": "Sudha",
    "level": 2,
    "sceneLabel": "Your street, Bengaluru",
    "teachMode": false,
    "rubric": [
      "small talk flow",
      "talking about yourself",
      "everyday household vocabulary",
      "warmth"
    ],
    "defaultSecretAgenda": [
      "introducing yourself",
      "family and work",
      "neighbourhood daily routine"
    ]
  },
  "hi-neighbour": {
    "id": "hi-neighbour",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "neighbour",
    "shop": "neighbour",
    "name": "Rekha",
    "level": 2,
    "sceneLabel": "Your gali, Dilli",
    "teachMode": false,
    "rubric": [
      "small talk flow",
      "talking about yourself",
      "everyday household vocabulary",
      "warmth"
    ],
    "defaultSecretAgenda": [
      "introducing yourself",
      "family and work",
      "neighbourhood daily routine"
    ]
  },
  "ta-neighbour": {
    "id": "ta-neighbour",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "neighbour",
    "shop": "neighbour",
    "name": "Vasanthi",
    "level": 2,
    "sceneLabel": "Your street, Chennai",
    "teachMode": false,
    "rubric": [
      "small talk flow",
      "talking about yourself",
      "everyday household vocabulary",
      "warmth"
    ],
    "defaultSecretAgenda": [
      "introducing yourself",
      "family and work",
      "neighbourhood daily routine"
    ]
  },
  "fr-neighbour": {
    "id": "fr-neighbour",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "neighbour",
    "shop": "neighbour",
    "name": "Anaïs",
    "level": 2,
    "sceneLabel": "Next door, Paris",
    "teachMode": false,
    "rubric": [
      "small talk flow",
      "talking about yourself",
      "everyday household vocabulary",
      "warmth"
    ],
    "defaultSecretAgenda": [
      "introducing yourself",
      "family and work",
      "neighbourhood daily routine"
    ]
  },
  "kn-landlord": {
    "id": "kn-landlord",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "landlord",
    "shop": "landlord",
    "name": "Murthy",
    "level": 3,
    "sceneLabel": "Your flat, Bengaluru",
    "teachMode": false,
    "rubric": [
      "making a complaint clearly",
      "money and date fluency",
      "negotiating politely",
      "standing your ground"
    ],
    "defaultSecretAgenda": [
      "household and repair vocabulary",
      "dates, months and money",
      "complaining and negotiating politely"
    ]
  },
  "hi-landlord": {
    "id": "hi-landlord",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "landlord",
    "shop": "landlord",
    "name": "Verma ji",
    "level": 3,
    "sceneLabel": "Your flat, Dilli",
    "teachMode": false,
    "rubric": [
      "making a complaint clearly",
      "money and date fluency",
      "negotiating politely",
      "standing your ground"
    ],
    "defaultSecretAgenda": [
      "household and repair vocabulary",
      "dates, months and money",
      "complaining and negotiating politely"
    ]
  },
  "ta-landlord": {
    "id": "ta-landlord",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "landlord",
    "shop": "landlord",
    "name": "Sekar",
    "level": 3,
    "sceneLabel": "Your flat, Chennai",
    "teachMode": false,
    "rubric": [
      "making a complaint clearly",
      "money and date fluency",
      "negotiating politely",
      "standing your ground"
    ],
    "defaultSecretAgenda": [
      "household and repair vocabulary",
      "dates, months and money",
      "complaining and negotiating politely"
    ]
  },
  "fr-landlord": {
    "id": "fr-landlord",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "landlord",
    "shop": "landlord",
    "name": "Paul",
    "level": 3,
    "sceneLabel": "Apartment visit, Paris",
    "teachMode": false,
    "rubric": [
      "making a complaint clearly",
      "money and date fluency",
      "negotiating politely",
      "standing your ground"
    ],
    "defaultSecretAgenda": [
      "household and repair vocabulary",
      "dates, months and money",
      "complaining and negotiating politely"
    ]
  },
  "kn-salon": {
    "id": "kn-salon",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "salon",
    "shop": "salon",
    "name": "Basava",
    "level": 2,
    "sceneLabel": "Salon, Bengaluru",
    "teachMode": false,
    "rubric": [
      "describing preferences",
      "saying no politely",
      "small talk",
      "comparison words"
    ],
    "defaultSecretAgenda": [
      "describing what you want",
      "more, less, shorter, longer",
      "opinions and small talk"
    ]
  },
  "hi-salon": {
    "id": "hi-salon",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "salon",
    "shop": "salon",
    "name": "Salim",
    "level": 2,
    "sceneLabel": "Salon, Dilli",
    "teachMode": false,
    "rubric": [
      "describing preferences",
      "saying no politely",
      "small talk",
      "comparison words"
    ],
    "defaultSecretAgenda": [
      "describing what you want",
      "more, less, shorter, longer",
      "opinions and small talk"
    ]
  },
  "ta-salon": {
    "id": "ta-salon",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "salon",
    "shop": "salon",
    "name": "Kumar",
    "level": 2,
    "sceneLabel": "Salon, Chennai",
    "teachMode": false,
    "rubric": [
      "describing preferences",
      "saying no politely",
      "small talk",
      "comparison words"
    ],
    "defaultSecretAgenda": [
      "describing what you want",
      "more, less, shorter, longer",
      "opinions and small talk"
    ]
  },
  "fr-salon": {
    "id": "fr-salon",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "salon",
    "shop": "salon",
    "name": "Thomas",
    "level": 2,
    "sceneLabel": "Hair salon, Paris",
    "teachMode": false,
    "rubric": [
      "describing preferences",
      "saying no politely",
      "small talk",
      "comparison words"
    ],
    "defaultSecretAgenda": [
      "describing what you want",
      "more, less, shorter, longer",
      "opinions and small talk"
    ]
  },
  "kn-pharmacy": {
    "id": "kn-pharmacy",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "pharmacy",
    "shop": "pharmacy",
    "name": "Prakash",
    "level": 2,
    "sceneLabel": "Medical store, Bengaluru",
    "teachMode": false,
    "rubric": [
      "explaining what you need",
      "understanding dose instructions",
      "numbers and money",
      "asking clarifying questions"
    ],
    "defaultSecretAgenda": [
      "medicine and symptom words",
      "numbers, doses and timing",
      "asking for something cheaper"
    ]
  },
  "hi-pharmacy": {
    "id": "hi-pharmacy",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "pharmacy",
    "shop": "pharmacy",
    "name": "Imran",
    "level": 2,
    "sceneLabel": "Medical store, Dilli",
    "teachMode": false,
    "rubric": [
      "explaining what you need",
      "understanding dose instructions",
      "numbers and money",
      "asking clarifying questions"
    ],
    "defaultSecretAgenda": [
      "medicine and symptom words",
      "numbers, doses and timing",
      "asking for something cheaper"
    ]
  },
  "ta-pharmacy": {
    "id": "ta-pharmacy",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "pharmacy",
    "shop": "pharmacy",
    "name": "Bala",
    "level": 2,
    "sceneLabel": "Medical store, Chennai",
    "teachMode": false,
    "rubric": [
      "explaining what you need",
      "understanding dose instructions",
      "numbers and money",
      "asking clarifying questions"
    ],
    "defaultSecretAgenda": [
      "medicine and symptom words",
      "numbers, doses and timing",
      "asking for something cheaper"
    ]
  },
  "fr-pharmacy": {
    "id": "fr-pharmacy",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "pharmacy",
    "shop": "pharmacy",
    "name": "Inès",
    "level": 2,
    "sceneLabel": "Pharmacie, Paris",
    "teachMode": false,
    "rubric": [
      "explaining what you need",
      "understanding dose instructions",
      "numbers and money",
      "asking clarifying questions"
    ],
    "defaultSecretAgenda": [
      "medicine and symptom words",
      "numbers, doses and timing",
      "asking for something cheaper"
    ]
  },
  "kn-cab": {
    "id": "kn-cab",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "cab",
    "shop": "cab",
    "name": "Naveen",
    "level": 2,
    "sceneLabel": "App cab, Bengaluru",
    "teachMode": false,
    "rubric": [
      "giving directions",
      "number fluency",
      "making a request",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "numbers and OTP digits",
      "directions and landmarks",
      "polite requests"
    ]
  },
  "hi-cab": {
    "id": "hi-cab",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "cab",
    "shop": "cab",
    "name": "Sandeep",
    "level": 2,
    "sceneLabel": "App cab, Dilli",
    "teachMode": false,
    "rubric": [
      "giving directions",
      "number fluency",
      "making a request",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "numbers and OTP digits",
      "directions and landmarks",
      "polite requests"
    ]
  },
  "ta-cab": {
    "id": "ta-cab",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "cab",
    "shop": "cab",
    "name": "Karthik",
    "level": 2,
    "sceneLabel": "App cab, Chennai",
    "teachMode": false,
    "rubric": [
      "giving directions",
      "number fluency",
      "making a request",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "numbers and OTP digits",
      "directions and landmarks",
      "polite requests"
    ]
  },
  "fr-cab": {
    "id": "fr-cab",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "cab",
    "shop": "cab",
    "name": "Mehdi",
    "level": 2,
    "sceneLabel": "Ride-app car, Paris",
    "teachMode": false,
    "rubric": [
      "giving directions",
      "number fluency",
      "making a request",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "numbers and OTP digits",
      "directions and landmarks",
      "polite requests"
    ]
  },
  "kn-hospital": {
    "id": "kn-hospital",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "hospital",
    "shop": "hospital",
    "name": "Shwetha",
    "level": 2,
    "sceneLabel": "Hospital help desk, Bengaluru",
    "teachMode": false,
    "rubric": [
      "asking where something is",
      "understanding directions",
      "numbers and floors",
      "describing why you came"
    ],
    "defaultSecretAgenda": [
      "hospital departments",
      "floors, directions and token numbers",
      "asking where something is"
    ]
  },
  "hi-hospital": {
    "id": "hi-hospital",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "hospital",
    "shop": "hospital",
    "name": "Neha",
    "level": 2,
    "sceneLabel": "Hospital help desk, Dilli",
    "teachMode": false,
    "rubric": [
      "asking where something is",
      "understanding directions",
      "numbers and floors",
      "describing why you came"
    ],
    "defaultSecretAgenda": [
      "hospital departments",
      "floors, directions and token numbers",
      "asking where something is"
    ]
  },
  "ta-hospital": {
    "id": "ta-hospital",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "hospital",
    "shop": "hospital",
    "name": "Priya",
    "level": 2,
    "sceneLabel": "Hospital help desk, Chennai",
    "teachMode": false,
    "rubric": [
      "asking where something is",
      "understanding directions",
      "numbers and floors",
      "describing why you came"
    ],
    "defaultSecretAgenda": [
      "hospital departments",
      "floors, directions and token numbers",
      "asking where something is"
    ]
  },
  "fr-hospital": {
    "id": "fr-hospital",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "hospital",
    "shop": "hospital",
    "name": "Claire",
    "level": 2,
    "sceneLabel": "Hospital reception, Paris",
    "teachMode": false,
    "rubric": [
      "asking where something is",
      "understanding directions",
      "numbers and floors",
      "describing why you came"
    ],
    "defaultSecretAgenda": [
      "hospital departments",
      "floors, directions and token numbers",
      "asking where something is"
    ]
  },
  "kn-insurance": {
    "id": "kn-insurance",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "insurance",
    "shop": "insurance",
    "name": "Raghavendra",
    "level": 3,
    "sceneLabel": "Health insurance advisor, Bengaluru",
    "teachMode": false,
    "rubric": [
      "asking clarifying questions",
      "number fluency with lakhs and percentages",
      "comparing options",
      "saying no politely"
    ],
    "defaultSecretAgenda": [
      "insurance and money words",
      "big numbers, lakhs and percentages",
      "asking clarifying questions"
    ]
  },
  "hi-insurance": {
    "id": "hi-insurance",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "insurance",
    "shop": "insurance",
    "name": "Rohit",
    "level": 3,
    "sceneLabel": "Health insurance advisor, Dilli",
    "teachMode": false,
    "rubric": [
      "asking clarifying questions",
      "number fluency with lakhs and percentages",
      "comparing options",
      "saying no politely"
    ],
    "defaultSecretAgenda": [
      "insurance and money words",
      "big numbers, lakhs and percentages",
      "asking clarifying questions"
    ]
  },
  "ta-insurance": {
    "id": "ta-insurance",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "insurance",
    "shop": "insurance",
    "name": "Senthil",
    "level": 3,
    "sceneLabel": "Health insurance advisor, Chennai",
    "teachMode": false,
    "rubric": [
      "asking clarifying questions",
      "number fluency with lakhs and percentages",
      "comparing options",
      "saying no politely"
    ],
    "defaultSecretAgenda": [
      "insurance and money words",
      "big numbers, lakhs and percentages",
      "asking clarifying questions"
    ]
  },
  "fr-insurance": {
    "id": "fr-insurance",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "insurance",
    "shop": "insurance",
    "name": "Antoine",
    "level": 3,
    "sceneLabel": "Mutuelle advisor, Paris",
    "teachMode": false,
    "rubric": [
      "asking clarifying questions",
      "number fluency with lakhs and percentages",
      "comparing options",
      "saying no politely"
    ],
    "defaultSecretAgenda": [
      "insurance and money words",
      "big numbers, lakhs and percentages",
      "asking clarifying questions"
    ]
  },
  "kn-claim": {
    "id": "kn-claim",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "claim",
    "shop": "claim",
    "name": "Nandini",
    "level": 3,
    "sceneLabel": "Insurance claims desk, Bengaluru",
    "teachMode": false,
    "rubric": [
      "staying polite and firm",
      "number and amount fluency",
      "asking for a review",
      "confirming next steps"
    ],
    "defaultSecretAgenda": [
      "money, amounts and dates",
      "polite firmness and negotiation",
      "documents and reference numbers"
    ]
  },
  "hi-claim": {
    "id": "hi-claim",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "claim",
    "shop": "claim",
    "name": "Kavita",
    "level": 3,
    "sceneLabel": "Insurance claims desk, Dilli",
    "teachMode": false,
    "rubric": [
      "staying polite and firm",
      "number and amount fluency",
      "asking for a review",
      "confirming next steps"
    ],
    "defaultSecretAgenda": [
      "money, amounts and dates",
      "polite firmness and negotiation",
      "documents and reference numbers"
    ]
  },
  "ta-claim": {
    "id": "ta-claim",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "claim",
    "shop": "claim",
    "name": "Revathi",
    "level": 3,
    "sceneLabel": "Insurance claims desk, Chennai",
    "teachMode": false,
    "rubric": [
      "staying polite and firm",
      "number and amount fluency",
      "asking for a review",
      "confirming next steps"
    ],
    "defaultSecretAgenda": [
      "money, amounts and dates",
      "polite firmness and negotiation",
      "documents and reference numbers"
    ]
  },
  "fr-claim": {
    "id": "fr-claim",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "claim",
    "shop": "claim",
    "name": "Sandrine",
    "level": 3,
    "sceneLabel": "Insurance claims line, Paris",
    "teachMode": false,
    "rubric": [
      "staying polite and firm",
      "number and amount fluency",
      "asking for a review",
      "confirming next steps"
    ],
    "defaultSecretAgenda": [
      "money, amounts and dates",
      "polite firmness and negotiation",
      "documents and reference numbers"
    ]
  },
  "kn-lesson": {
    "id": "kn-lesson",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "lesson",
    "shop": "lesson",
    "name": "Prakash",
    "level": 2,
    "sceneLabel": "Music class, Nathaniel School",
    "teachMode": false,
    "rubric": [
      "music vocabulary",
      "counting fluency",
      "following instructions",
      "asking the teacher questions"
    ],
    "defaultSecretAgenda": [
      "music words in the target language",
      "counting and numbers one to eight",
      "understanding instructions"
    ]
  },
  "hi-lesson": {
    "id": "hi-lesson",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "lesson",
    "shop": "lesson",
    "name": "Rahul",
    "level": 2,
    "sceneLabel": "Music class, Nathaniel School",
    "teachMode": false,
    "rubric": [
      "music vocabulary",
      "counting fluency",
      "following instructions",
      "asking the teacher questions"
    ],
    "defaultSecretAgenda": [
      "music words in the target language",
      "counting and numbers one to eight",
      "understanding instructions"
    ]
  },
  "ta-lesson": {
    "id": "ta-lesson",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "lesson",
    "shop": "lesson",
    "name": "Vijay",
    "level": 2,
    "sceneLabel": "Music class, Nathaniel School",
    "teachMode": false,
    "rubric": [
      "music vocabulary",
      "counting fluency",
      "following instructions",
      "asking the teacher questions"
    ],
    "defaultSecretAgenda": [
      "music words in the target language",
      "counting and numbers one to eight",
      "understanding instructions"
    ]
  },
  "fr-lesson": {
    "id": "fr-lesson",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "lesson",
    "shop": "lesson",
    "name": "Julien",
    "level": 2,
    "sceneLabel": "Music class, Nathaniel School",
    "teachMode": false,
    "rubric": [
      "music vocabulary",
      "counting fluency",
      "following instructions",
      "asking the teacher questions"
    ],
    "defaultSecretAgenda": [
      "music words in the target language",
      "counting and numbers one to eight",
      "understanding instructions"
    ]
  },
  "kn-desk": {
    "id": "kn-desk",
    "language": "kn",
    "languageCode": "kn-IN",
    "languageName": "Kannada",
    "scenario": "desk",
    "shop": "desk",
    "name": "Ananya",
    "level": 2,
    "sceneLabel": "Nathaniel School front desk",
    "teachMode": false,
    "rubric": [
      "asking questions",
      "understanding answers",
      "music and school vocabulary",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "asking questions politely",
      "days, times and numbers",
      "music and school words"
    ]
  },
  "hi-desk": {
    "id": "hi-desk",
    "language": "hi",
    "languageCode": "hi-IN",
    "languageName": "Hindi",
    "scenario": "desk",
    "shop": "desk",
    "name": "Ritika",
    "level": 2,
    "sceneLabel": "Nathaniel School front desk",
    "teachMode": false,
    "rubric": [
      "asking questions",
      "understanding answers",
      "music and school vocabulary",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "asking questions politely",
      "days, times and numbers",
      "music and school words"
    ]
  },
  "ta-desk": {
    "id": "ta-desk",
    "language": "ta",
    "languageCode": "ta-IN",
    "languageName": "Tamil",
    "scenario": "desk",
    "shop": "desk",
    "name": "Divya",
    "level": 2,
    "sceneLabel": "Nathaniel School front desk",
    "teachMode": false,
    "rubric": [
      "asking questions",
      "understanding answers",
      "music and school vocabulary",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "asking questions politely",
      "days, times and numbers",
      "music and school words"
    ]
  },
  "fr-desk": {
    "id": "fr-desk",
    "language": "fr",
    "languageCode": "fr-FR",
    "languageName": "French",
    "scenario": "desk",
    "shop": "desk",
    "name": "Léa",
    "level": 2,
    "sceneLabel": "Nathaniel School front desk",
    "teachMode": false,
    "rubric": [
      "asking questions",
      "understanding answers",
      "music and school vocabulary",
      "politeness"
    ],
    "defaultSecretAgenda": [
      "asking questions politely",
      "days, times and numbers",
      "music and school words"
    ]
  }
};

// Which scenario each lit shopfront opens.
export const SHOP_SCENARIO: Record<string, string> = {
  "auto": "auto",
  "gate": "delivery",
  "phone": "care",
  "airport": "airport",
  "chai": "chai",
  "music": "teach",
  "market": "market",
  "kirana": "kirana",
  "clinic": "doctor",
  "restaurant": "restaurant",
  "neighbour": "neighbour",
  "landlord": "landlord",
  "salon": "salon",
  "pharmacy": "pharmacy",
  "cab": "cab",
  "hospital": "hospital",
  "insurance": "insurance",
  "claim": "claim",
  "lesson": "lesson",
  "desk": "desk"
};

export function personaId(shop: string, lang: string): string | null {
  const scenario = SHOP_SCENARIO[shop];
  if (!scenario) return null;
  const id = `${lang}-${scenario}`;
  return PERSONAS[id] ? id : null;
}
